### ISSUE TITLE
message limit

### ISSUE THREAD

**Issue by bobbythehuman** [ThiagoFPMR/Scraper-Bot#2]
what is the message limit since discord has a file size limit. i started one and  i estimated it to take about 10min and it has been 30mins and still going.

**Comment by ThiagoFPMR** [comment]
How many messages did you try to read?

**Comment by bobbythehuman** [comment]
It was 71k messages and it did finish it just to about 50mins, but still wondering what the limit of the amount of message you could get before it stops working.

**Comment by ThiagoFPMR** [comment]
In terms of the exact amount of messages, I think it's hard to say because the size of each individual message varies, but the file size limit for bots in Discord is 50MB. I plan on making it so it splits the data into two or more separate downloads if the file size reaches that threshold so there won't be a limit to how many messages can be read.
